# 头部导航 Header
menu:
  归档: /archives
  DevOps: /tags/DevOps
  机器学习: /tags/Machine-Learning
  经济学人: /tags/Economist
  Policy&Law: /tags/Policy-Law
  图表: /2017/07/06/Visualization
  电子书: /2017/02/09/eBook
  关于: /2016/05/31/AboutMe
  TechBlog: https://riboseyim.com
rss: /atom.xml

# footer底部显示联系邮箱（在博客配置文件下添加email配置也是一样的效果）
email: 'riboseyim@gmail.com'

# 内容 Content
excerpt_link: 继续阅读全文 »
fancybox: true

# 启用social widgets时有效
# 社交widget文本字体，不填写则不显示title
social_title: Follow me
# Social links 社交链接
social:
  homesite: https://riboseyim.github.io
  github: https://github.com/riboseyim
  zhihu: https://www.zhihu.com/people/riboseyim
  email: riboseyim@gmail.com
  linkedin: https://www.linkedin.com/in/riboseyim

# WeChat 微信公众号二维码url
wechat_url: ./RiboseYim_WeChat.png ## 启用wechat widget才会生效

# Friendly links 友情链接
links:
    简书: https://www.jianshu.com/u/8cc1dba4bc96
    电子书《Linux Perf Master》: https://www.gitbook.com/book/riboseyim/linux-perf-master/details
    系统运维专家: https://www.jianshu.com/c/9a817d8a67ea
    网络与信息安全: https://www.jianshu.com/c/0886ffd76168
    经济学人翻译社: https://www.jianshu.com/c/f2ea0605db4b
    快捷方式: https://riboseyim.github.io/2017/11/16/QuickStart
    索引目录: https://riboseyim.github.io/2017/05/26/Catalog

# 侧边栏 Sidebar，目前仅支持right
sidebar: right
# 目录展示位置，有两种选择，post为文章内部右侧；widget为sidebar形式展示，在markdown文件中通过toc:false可以指定某文章不展示目录
content_position: widget
# true目录将会浮动固定位置，false则相反，当且仅当content_position=widget时该设置值有效
content_display_fixed: true

# 文章底部推荐文章数,false关闭
random_posts: 10

widgets:
- social
- post_content
- category
- tagcloud
- recent_posts
- archive
- friendly_link
- wechat

# 提供以下内置组件
# - post_content      # 文章目录
# - category          # 归类
# - tag               # 标签
# - tagcloud          # 云标签
# - archives          # 归档
# - recent_posts      # 最新文章
# - lastest_comments  # 最新评论
# - hot_comment_posts # 热评文章
# - friendly_link     # 友情链接
# - wechat            # 微信公众号


# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
# 分类是否显示文章数量
show_count: true

# 标签云TagClound
# 如果启动，则标签云颜色为随机
tagcloud_color: true

# MathJax Support
# 设置enable属性为true即可开启mathjax
# per_page如果为true表示所有文章都设置支持mathjax，如果为false，则在需要支持mathjax的文章加上mathjax: true
mathjax:
  enable: true
  per_page: false
  cdn: https://riboseyim.com/MathJax.js?config=TeX-AMS-MML_HTMLorMML



# 其他参数
google_analytics: UA-129742531-2
favicon: /favicon.ico


# comments 评论插件
# 关闭统一为 false

## 网易云跟帖
### 使用说明 http://cafe.giscafer.com/2017/04/14/gentie-test/
gentie_productKey:

## 畅言 (不使用请将appid和appkey都设空或者false)
### 使用说明：http://changyan.kuaizhan.com/static/help/
changyan_appid: false  ##appid
changyan_appkey: false  ##appkey
## 友言
### 使用说明
### 填写友言用户ID http://www.uyan.cc/sites
youyan_uid: false

# gitment
## 教程：https://imsun.net/posts/gitment-introduction/ 网站上进行查看
gitment:
  enable: true #如果不使用则设置false关闭
  owner: riboseyim # 你的github名称或者id id的获取方式为https://api.github.com/users/forvoid（你的名称）中的id极为github id
  repo: riboseyim.com.comment # 你的留言存放的位置 我的是放在我的github的github page上面
  client_id: 43e9627ca705c8c77302 # Register a new OAuth application https://github.com/settings/applications/new
  client_secret: 762251955af8f821c334c7a5bd33c85c3707edff

## disqus
disqus_shortname: false

google_plus:
fb_admins:
fb_app_id:
